In [1]:
import dispindiffs
import polars as pl
import pandas as pd
import numpy as np

In [2]:
iso3 = pd.read_csv("./dat/iso3.csv") # https://data.apps.fao.org/catalog/dataset/iso-3-code-list-global-region-country
iso3_to_name = dict(zip(iso3["iso3"], iso3["name"]))

df = pl.read_csv("./dat/sitc_country_country_year.csv") # https://atlas.hks.harvard.edu/data-downloads - "Country Trade by Partner"
df = df.filter(pl.col("year")>=2020)

In [3]:
elist = df.group_by(["country_iso3_code", "partner_iso3_code"]).agg(pl.col("export_value").sum())
elist = elist.filter(pl.col("export_value")>0)
elist = elist.with_columns(pl.col('export_value')/1000) # to prevent overflow
N_T = len(set(elist["country_iso3_code"]) | set(elist["partner_iso3_code"]))
E_T = len(elist)
print(N_T, E_T)

235 32296

In [4]:
Trade = dispindiffs.DisparityInDifferences(elist, source="country_iso3_code", target="partner_iso3_code", weight="export_value", n_samples=10000)
Trade.calc_disp()
Trade.calc_nc()
Trade.calc_disp_in_diffs()

Merging bilateral relations
Generating pre-sampled values from beta distributions
Calculating statistical significance

100%|██████████| 13966/13966 [00:00<00:00, 54655.67it/s]

Done

### Disparity Filter

In [5]:
n_nodes_edges_by_th = []
for th in [10**(-k) for k in np.arange(20, -0.1, -0.25)]:
    bb, th, N, E = Trade.extr_disp_backbone(th=th)    
    n_nodes_edges_by_th.append((th, N, E))
pd.DataFrame(n_nodes_edges_by_th, columns=["th", "n_nodes", "n_edges"]).to_csv("./outputs/trade_disp_info_by_th.csv", index=False)

In [6]:
disp_backbone, _, _, _ = Trade.extr_disp_backbone(th=0.01)

### Noise corrected

In [9]:
n_nodes_edges_by_delta = []
for delta in np.arange(0, 1001, 10):
    bb, th, N, E = Trade.extr_nc_backbone(delta=delta)    
    n_nodes_edges_by_delta.append((th, N, E))
pd.DataFrame(n_nodes_edges_by_delta, columns=["delta", "n_nodes", "n_edges"]).to_csv("./outputs/trade_bc_info_by_delta.csv", index=False)

In [10]:
nc_backbone, _, _, _  = Trade.extr_nc_backbone(delta=2.32)

### Disparity-in-Differences

In [11]:
n_nodes_edges_by_th = []
for th in [10**(-k) for k in np.arange(20, -0.1, -0.25)]:
    bb, th, N, E = Trade.extr_disp_in_diffs_backbone(th=th)    
    n_nodes_edges_by_th.append((th, N, E))
pd.DataFrame(n_nodes_edges_by_th, columns=["th", "n_nodes", "n_edges"]).to_csv("./outputs/trade_disp_in_diffs_info_by_th.csv", index=False)

In [12]:
disp_in_diffs_backbone, _, _, _  = Trade.extr_disp_in_diffs_backbone(th=0.01)

### Comparisons

#### Top countries with respect to the number of incoming edges

In [13]:
top_disp = disp_backbone.group_by("target").agg(pl.len()).sort("len", descending=True)
top_disp = top_disp.with_columns(pl.col("target").replace_strict(iso3_to_name, default="").alias("name"))
print(list(top_disp["name"][:10]))

['United States of America', 'China', 'Germany', 'Netherlands', 'United Kingdom', 'India', 'Italy', 'France', 'United Arab Emirates', 'Spain']

In [14]:
top_nc = nc_backbone.group_by("target").agg(pl.len()).sort("len", descending=True)
top_nc = top_nc.with_columns(pl.col("target").replace_strict(iso3_to_name, default="").alias("name"))
print(list(top_nc["name"][:10]))

['India', 'United Arab Emirates', 'Spain', 'Türkiye', 'China', 'United Kingdom', 'Italy', 'Netherlands', 'France', 'Poland']

In [15]:
top_disp_in_diffs = disp_in_diffs_backbone.group_by("target").agg(pl.len()).sort("len", descending=True)
top_disp_in_diffs = top_disp_in_diffs.with_columns(pl.col("target").replace_strict(iso3_to_name, default="").alias("name"))
print(list(top_disp_in_diffs["name"][:10]))

['United States of America', 'China', 'Germany', 'India', 'Netherlands', 'United Kingdom', 'Italy', 'France', 'United Arab Emirates', 'Japan']

In [16]:
top_comparison = pd.DataFrame({
    "disp": list(top_disp["name"])[:30],
    "nc": list(top_nc["name"])[:30],
    "disp_in_diffs": list(top_disp_in_diffs["name"])[:30],
})
top_comparison.head(10)

                       disp                    nc             disp_in_diffs
0  United States of America                 India  United States of America
1                     China  United Arab Emirates                     China
2                   Germany                 Spain                   Germany
3               Netherlands               Türkiye                     India
4            United Kingdom                 China               Netherlands
5                     India        United Kingdom            United Kingdom
6                     Italy                 Italy                     Italy
7                    France           Netherlands                    France
8      United Arab Emirates                France      United Arab Emirates
9                     Spain                Poland                     Japan

#### Mexico case

In [17]:
disp_backbone.filter((pl.col("source")=="MEX") | (pl.col("target")=="MEX")).to_pandas().sort_values(by="source")

   source target        weight      sum_w_ij      p_ij  k_i_out     disp_alpha
9     BRA    MEX  2.570157e+07  1.128769e+09  0.022770      233   4.778601e-03
4     CHN    MEX  2.757818e+08  1.230503e+10  0.022412      212   8.372890e-03
5     COL    MEX  5.903510e+06  1.737341e+08  0.033980      198   1.102179e-03
0     GTM    MEX  2.436617e+06  5.341162e+07  0.045620      179   2.457130e-04
10    HKG    MEX  1.629864e+07  7.132059e+08  0.022853      204   9.159951e-03
2     HND    MEX  1.444978e+06  3.382007e+07  0.042725      145   1.858910e-03
1     MEX    CAN  8.803562e+07  2.095979e+09  0.042002      181   4.421968e-04
3     MEX    USA  1.656354e+09  2.095979e+09  0.790253      181  8.036758e-123
8     NIC    MEX  3.094908e+06  2.743676e+07  0.112802      151   1.596318e-08
7     TTO    MEX  1.048687e+06  3.618928e+07  0.028978      167   7.586440e-03
6     USA    MEX  1.134531e+09  7.021600e+09  0.161577      224   8.555923e-18

In [18]:
nc_backbone.filter((pl.col("source")=="MEX") | (pl.col("target")=="MEX")).to_pandas().sort_values(by="source")[["source", "target"]]

   source target
4     ABW    MEX
15    COL    MEX
0     GTM    MEX
3     HND    MEX
10    HTI    MEX
5     MEX    HND
6     MEX    DOM
7     MEX    COL
8     MEX    USA
19    MEX    GTM
11    MEX    SLV
12    MEX    CRI
13    MEX    BLZ
14    MEX    PER
1     MEX    NIC
2     MEX    CAN
20    MEX    CUB
18    NIC    MEX
9     SLV    MEX
17    TTO    MEX
16    USA    MEX

In [19]:
disp_in_diffs_backbone.filter((pl.col("source")=="MEX") | (pl.col("target")=="MEX")).to_pandas().sort_values(by="source")

  source target
1    COL    MEX
2    GTM    MEX
3    HND    MEX
0    MEX    CAN
5    MEX    USA
4    NIC    MEX